from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Protocol, Iterable, Optional
from uuid import UUID

from app.schemas.user import User, UserCreate, UserPublic
from app.schemas.files import FileMeta, FileMetaCreate
from app.schemas.feedback import Feedback, FeedbackCreate, FeedbackUpdate
from app.schemas.groups import Group, GroupCreate, GroupMembership


class UsersRepository(Protocol):
    async def create(self, data: UserCreate) -> User: ...
    async def get_by_email(self, email: str) -> Optional[User]: ...
    async def get(self, user_id: UUID) -> Optional[User]: ...
    async def list(self) -> list[User]: ...
    async def verify(self, user_id: UUID) -> None: ...


class FilesRepository(Protocol):
    async def create(self, data: FileMetaCreate, file_id: Optional[UUID] = None) -> FileMeta: ...
    async def get(self, file_id: UUID) -> Optional[FileMeta]: ...
    async def list(self) -> list[FileMeta]: ...
    async def list_by_uploader(self, user_id: UUID) -> list[FileMeta]: ...


class FeedbackRepository(Protocol):
    async def create(self, data: FeedbackCreate) -> Feedback: ...
    async def update(self, feedback_id: UUID, data: FeedbackUpdate) -> Optional[Feedback]: ...
    async def list_for_file(self, file_id: UUID) -> list[Feedback]: ...
    async def average_for_file(self, file_id: UUID) -> Optional[float]: ...


class GroupsRepository(Protocol):
    async def create(self, data: GroupCreate) -> Group: ...
    async def join(self, group_id: UUID, user_id: UUID) -> GroupMembership: ...
    async def list_groups(self) -> list[Group]: ...
    async def members(self, group_id: UUID) -> list[UserPublic]: ...
